version: "3.8"

services:
  openstreetmap-web:
    image: overv/openstreetmap-tile-server
    container_name: openstreetmap-web
    restart: always
    ports:
      - 8081:80
    volumes: 
      - ./osm-data/_data/:/data/database/
      - ./osm-tiles:/data/tiles/
    command: "run"